### ISSUE TITLE
Legal notice

### ISSUE THREAD

**Issue by bitionaire** [scrumlr/scrumlr.io#68]
All mandatory legal notices must be added.

* Reachable from every site
* Reachable with at most 2-clicks 
* Reachable via text-links in the same language as the website (Images are not allowed for a11y reasons)
* Reachable without necessity for JavaScript (not important without SSR)

## Mandatory

* Imprint
  * Full name & address
  * E-Mail & Tel.
* Privacy policy / Data protection notice
  * _"Who receives the collected information"_, _"Information about third-party sites that might collect information"_: Analytics
  * Purpose of data collections
  * List of recipients (countries)
  * Information about Cookies
* Terms and Conditions of Use
  * _"How to credit content and images from the site"_
  * ...

## Optional

* Copyright Notices on third-party content (if present)
* Disclaimer (if external links are present)
* [Cookie consent](http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm)

## Examples

<img width="341" alt="Trello" src="https://user-images.githubusercontent.com/1539948/40304913-b81884a2-5cf8-11e8-92ff-fb7c47dd2149.png">

## Sources

* https://www.lifewire.com/legal-pages-for-websites-3468973
* http://ec.europa.eu/ipg/basics/legal/index_en.htm
* https://www.ihk-wiesbaden.de/recht/rechtsberatung/Internetrecht-und-Werbung/Internetauftritt_Rechtliche_Anforderungen_und_Pflichten/1255572

**Comment by wlbr** [comment]
DSVGO gilt ab 25.5.18. Ihr sammelt mindestens Logindaten/Emailadressen.
--> Datenschutzerklärung und Cookieerläuterungen Pflicht.
Die Site nutzt Google Analytics --> Datenschutzerklärung, Anpassungen in der Analytics Console.

Siehe https://www.heise.de/ct/ausgabe/2018-11-Die-Umsetzung-der-DSGVO-Vorgaben-laeuft-nicht-rund-4039713.html?wt_mc=print.ct.2018.11.76#zsdb-article-links
insb. 
https://datenschutz-generator.de/

**Comment by bitionaire** [comment]
Ich habe mal Analytics sicherheitshalber rausgenommen, Cookies fallen somit vorläufig keine mehr an. Da im aktuellen Zustand keine "Gewinnabsicht" vorhanden ist (z.B. durch Werbung), die Seite nicht aktiv im Internet beworben wird, mit "Beta" gekennzeichnet ist und kein Gewerbe dahinter steht, fällt sie meinen Recherchen nach derzeit aber auch nicht unter die DSVGO-Pflicht. Ich mag mich aber irren, bin schließlich kein Jurist :)
Die Seite ist derzeit anonym nutzbar und ein Login über die Provider oder die Eingabe einer E-Mail Adresse keine Pflicht.

**Comment by wlbr** [comment]
Aber wenn jemand Emails benutzt, dann wird die Adresse gespeichert. Und dann muss man Auskunft geben, zu welchem Zweck die Adressen abgelegt werden. Und man m.E. das Recht auf Vergessenwerden unterstützen, im Zweifelsfall auch händisch. D.h. jemand kann fragen, was alles für Daten zu ihm im System sind und kann das Löschen beantragen.
Mit der Gewinnabsicht hast Du Recht. Evtl. ist das Tool trotzdem im Graubereich. Ich würde zumindest die Datenschutzerklärung generieren und verlinken.  Siehe https://www.bsc-karlsruhe.de/administratives
Und das Impressum muss m.E. sowieso sein. 

Aber auch ich bin kein Experte. Das hier wurde als Simpelpragmatismus empfohlen: https://lutz.donnerhacke.de/Blog/Der-praktische-Weg-zur-DSGVO

Over and out.
